name: danci
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # âœ… æ ¸å¿ƒä¾èµ–
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  fl_chart: ^0.68.0
  url_launcher: ^6.3.0
  flutter_tts: ^4.0.0    # ğŸ‘ˆ å·²æ›´æ–°ï¼šç”¨äºç¦»çº¿å‘éŸ³

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
    - assets/data/
    - assets/zsm/  